# Maven

trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - script: taskkill /f /im chromedriver.exe
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'aqualityautomation'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: |
        sonar.coverage.exclusions=**/**
  - task: ScreenResolutionUtility@1
    inputs:
      displaySettings: 'optimal'

  - task: Windows Application Driver@0
    displayName: 'Start WinAppDriver'
    inputs:
      OperationType: 'Start'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test -Dprofile=local'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - task: Windows Application Driver@0
    displayName: stop WinAppDriver
    inputs:
      OperationType: 'Stop'
