trigger:
  - master

pool:
  vmImage: 'windows-latest'

jobs:
- job: sonar
  displayName: Analyse code with SonarQube

  steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis'
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'aqualityautomation'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: |
        sonar.coverage.exclusions=**/**

  - task: Maven@3
    displayName: 'Build project'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean'

  - task: SonarCloudAnalyze@1
    displayName: 'Run SonarCloud code analysis'
    continueOnError: true

  - task: SonarCloudPublish@1
    displayName: 'Publish SonarCloud quality gate results'
    inputs:
      pollingTimeoutSec: '300'

- job: tests
  displayName: Run tests

  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.x'

  - task: CmdLine@2
    displayName: 'Configure Appium'
    inputs:
      script: |
          echo "Configuring Environment"
          export PATH=$PATH:$JAVA_HOME/bin

          echo "JAVA_HOME: ${JAVA_HOME}"
          echo "PATH: ${PATH}"

          echo "Installing Appium"
          npm install -g appium@next
          ln -fs /usr/local/lib/node_modules/appium/build/lib/main.js /usr/local/bin/appium
          chmod +x /usr/local/bin/appium
          export PATH=$PATH:/usr/local/bin/appium
          appium --version
          echo "Appium installed"

          echo "Installing and Running Appium doctor"
          npm install -g request@2.34.0
          npm install -g appium-doctor@1.15.1
          ln -fs /usr/local/lib/node_modules/appium-doctor/appium-doctor.js /usr/local/bin/appium-doctor
          chmod +x /usr/local/bin/appium-doctor
          export PATH=$PATH:/usr/local/bin/appium-doctor
          appium-doctor
          echo "Appium doctor installed and executed"

          echo "Install Appium Windows Driver"
          appium driver install windows
          echo "Appium Windows Driver installed"

  - task: CmdLine@2
    displayName: 'Start Appium server'
    inputs:
      script: |
        appium &
        echo "Appium server started"

  - task: ScreenResolutionUtility@1
    displayName: 'Set optimal screen resolution'
    inputs:
      displaySettings: 'optimal'

  - task: Maven@3
    displayName: 'Run tests'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test -Dprofile=local'
