trigger:
  - master

pool:
  vmImage: 'windows-latest'

jobs:
- job: sonar
  displayName: Analyse code with SonarQube

  steps:
  - task: SonarCloudPrepare@2
    displayName: 'Prepare SonarCloud analysis'
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'aqualityautomation'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: 'sonar.coverage.exclusions=**/**'

  - task: Maven@4
    displayName: 'Build project'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean'
      options: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: SonarCloudAnalyze@2
    inputs:
      jdkversion: 'JAVA_HOME'
    displayName: 'Run SonarCloud code analysis'
    continueOnError: true

  - task: SonarCloudPublish@2
    displayName: 'Publish SonarCloud quality gate results'
    inputs:
      pollingTimeoutSec: '300'

- job: tests
  displayName: Run tests

  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.x'

  - task: CmdLine@2
    displayName: 'Install Appium'
    inputs:
      script: |
          echo "Installing Appium"
          npm install -g appium@next
          appium --version
          echo "Appium installed"

  - task: CmdLine@2
    displayName: 'Install and Run Appium doctor'
    inputs:
      script: |
        echo "Installing and Running Appium doctor"
        npm install -g request@2.34.0
        npm install -g appium-doctor@1.15.1
        appium-doctor
        echo "Appium doctor installed and executed"

  - task: CmdLine@2
    displayName: 'Install Appium Windows Driver'
    inputs:
      script: |
        echo "Installing Appium Windows Driver"
        appium driver install --source=npm appium-windows-driver
        appium driver list
        echo "Appium Windows Driver installed"

  - task: CmdLine@2
    displayName: 'Start Appium server'
    inputs:
      script: |
        start cmd.exe @cmd /k "appium"
        echo "Appium server started"

  - task: ScreenResolutionUtility@1
    displayName: 'Set optimal screen resolution'
    inputs:
      displaySettings: 'optimal'

  - task: Maven@4
    displayName: 'Run tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test -Dprofile=local'
      options: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
