trigger:
  - master

pool:
  vmImage: 'windows-latest'

jobs:
- job: tests
  displayName: Run tests

  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.x'

  - task: CmdLine@2
    displayName: 'Configure Appium'
    inputs:
      script: |
          echo "Installing Appium"
          npm install -g appium@next
          appium --version
          echo "Appium installed"

  - task: CmdLine@2
    displayName: 'Installing and Running Appium doctor'
    inputs:
      script: |
        echo "Installing and Running Appium doctor"
        npm install -g request@2.34.0
        npm install -g appium-doctor@1.15.1
        appium-doctor
        echo "Appium doctor installed and executed"

  - task: CmdLine@2
    displayName: 'Install Appium Windows Driver'
    inputs:
      script: |
        echo "Install Appium Windows Driver"
        appium driver install windows
        appium driver list
        echo "Appium Windows Driver installed"

  - task: CmdLine@2
    displayName: 'Start Appium server'
    inputs:
      script: |
        start cmd.exe @cmd /k "appium"

  - task: ScreenResolutionUtility@1
    displayName: 'Set optimal screen resolution'
    inputs:
      displaySettings: 'optimal'

  - task: Maven@3
    displayName: 'Run tests'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test -Dprofile=local'
